Repository julien-duponchelle/python-mysql-replication, pull requests merged in 2023-10, with the labels that each got.

#494 v0.45 bug fix json object and array
  pymysqlreplication/event.py
  pymysqlreplication/packet.py
  pymysqlreplication/tests/test_basic.py
  pymysqlreplication/tests/test_data_type.py
  pymysqlreplication/util/__init__.py
  pymysqlreplication/util/bytes.py
Labels: hacktoberfest-accepted

#498 update logo svg file
  logo.svg
Labels: hacktoberfest-accepted

#501 Delete print code
  .readthedocs.yaml
  pymysqlreplication/tests/test_data_type.py
Labels: hacktoberfest-accepted

#516 fix last order column only when DML
  pymysqlreplication/row_event.py
Labels: hacktoberfest, release-1.0.3

#489 Distinguish ambiguous column value of `None`
  pymysqlreplication/constants/NONE_SOURCE.py
  pymysqlreplication/row_event.py
  pymysqlreplication/tests/test_basic.py
Labels: release-1.0.3

#534 ,closes #525
  pymysqlreplication/row_event.py
Labels: hacktoberfest

#551 Add workflow_dispatch to GitHub Actions
  .github/workflows/lint.yml
  .github/workflows/pytest.yml
Labels: hacktoberfest

#518 python2 minor fix
  pymysqlreplication/bitmap.py
  pymysqlreplication/tests/base.py
  pymysqlreplication/tests/benchmark.py
  pymysqlreplication/tests/test_data_type.py
Labels: release-1.0.3

#521 Feature/partial update row event
  pymysqlreplication/binlogstream.py
  pymysqlreplication/constants/BINLOG.py
  pymysqlreplication/constants/NONE_SOURCE.py
  pymysqlreplication/json_binary.py
  pymysqlreplication/packet.py
  pymysqlreplication/row_event.py
  pymysqlreplication/tests/test_basic.py
  pymysqlreplication/util/bytes.py
Labels: hacktoberfest-accepted
